version: '3'
volumes:
  database:
  cache:

services:

  postgres:
    image: postgres:14.2
    restart: always
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data
      - ./docker/database/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: adviser
      POSTGRES_USER: adviser
      DATABASES: adviser

  ollama:
    build:
      context: .
      dockerfile: ./Dockerfile.ollama
    image: ollama
    container_name: ollama
    entrypoint: /tmp/run-ollama.sh
    environment:
      - OLLAMA_HOST=0.0.0.0
    ports:
      - 11434:11434
    volumes:
      - ./docker/ollama/app:/app/
      - ./docker/ollama/ollama:/root/.ollama
    tty: true
    restart: always
#Uncomment to enable GPU capabilities (https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html)
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
